name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.x' ]
      fail-fast: false
    name: Python ${{ matrix.python-version }} Packaging Test

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel virtualenv pyang
        sudo apt-get install libxml2-dev libxslt1-dev

    - name: Run test
      run: tests/packaging.sh
